name: Build
on: workflow_dispatch
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            make: make windows64 CC=gcc
            arch: x86_64
          - os: ubuntu-latest
            make: make linux64
            arch: x86_64
          - os: macos-latest
            make: |
              clang --version
              make osx-arm64 MACOSX_DEPLOYMENT_TARGET=11.0
              make osx-x86_64 MACOSX_DEPLOYMENT_TARGET=10.14
              make osx64
            arch: x86_64-arm64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build artifact
        run: ${{ matrix.make }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}_${{ matrix.arch }}
          path: build/*/lua*.*

