name: Build
on: workflow_dispatch
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            make: windows64 CC=gcc
            arch: x86_64
          - os: ubuntu-latest
            make: linux64
            arch: x86_64
          - os: macos-latest
            make: osx MACOSX_DEPLOYMENT_TARGET=10.14
            arch: x86_64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build artifact
        env:
          MAKE_ARGS: ${{ matrix.make || '' }}
        run: make $MAKE_ARGS
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}_${{ matrix.arch }}
          path: build/*/lua*.*

